repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v6.0.0'
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-builtin-literals
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace{% if cookiecutter.code_formatter == 'black' %}
  - repo: https://github.com/psf/black
    rev: '25.1.0'
    hooks:
      - id: black
        language_version: python3.10
        exclude: ^notebooks
  - repo: https://github.com/pycqa/isort
    rev: '5.13.2'
    hooks:
      - id: isort
  - repo: https://github.com/asottile/pyupgrade
    rev: 'v3.20.0'
    hooks:
      - id: pyupgrade
        args: [ --py310-plus ]{% elif cookiecutter.code_formatter == 'ruff' %}
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.12.2'
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format{% else %}
  - repo: https://github.com/pycqa/isort
    rev: '5.13.2'
    hooks:
      - id: isort
  - repo: https://github.com/asottile/pyupgrade
    rev: 'v3.20.0'
    hooks:
      - id: pyupgrade
        args: [ --py310-plus ]{% endif %}
