version: '3'

services:
  {{ cookiecutter.project_slug }}:
    image: 'at/{{ cookiecutter.project_slug }}:latest'
    build:
      context: .{% if cookiecutter.package_manager != 'poetry' %}
      args:
        PYTHON_IMAGE_TAG: {% if cookiecutter.package_manager == 'conda' %}4.8.2"{% else %}"3.8-stretch"{% endif %}{% endif %}
    {% if cookiecutter.config_file == 'hocon' %}
    environment:
      ENV: dev
      USERNAME: ${USERNAME:-dear user of the at-python-template}
    {% endif %}
    command: '{% if cookiecutter.create_cli == 'yes' %}--help{% endif %}'
    tty: true
