ARG PYTHON_VERSION=3.13
FROM python:${PYTHON_VERSION}-bullseye
LABEL maintainer="{{ cookiecutter.company_name if cookiecutter.company_name else cookiecutter.full_name }}"

WORKDIR /app
COPY requirements.txt setup.py ./
RUN pip install -r requirements.txt --no-cache-dir --prefer-binary
COPY ./src ./src
COPY README.md ./
RUN pip install .

{%- if cookiecutter.ui_framework == 'chainlit' %}
EXPOSE 8000
CMD ["chainlit", "run", "src/{{ cookiecutter.module_name }}/ui/app.py", "-h"]
{%- elif cookiecutter.ui_framework == 'streamlit' %}
EXPOSE 8501
CMD ["streamlit", "run", "src/{{ cookiecutter.module_name }}/ui/app.py"]
{%- else %}
ENTRYPOINT ["python", "-OO", "-m", "{{ cookiecutter.module_name }}"]
{%- endif %}
