version: '3'

services:
  {{ cookiecutter.project_slug }}:
    image: 'at/{{ cookiecutter.project_slug }}:latest'
    build:
      context: .
      args:
        {% if cookiecutter.package_manager == 'uv' %}
        PYTHON_IMAGE_TAG: "3.11-bookworm"
        {% elif cookiecutter.package_manager == 'poetry' %}
        PYTHON_IMAGE_TAG: "3.9-bullseye"
        {% elif cookiecutter.package_manager == 'conda' %}
        PYTHON_IMAGE_TAG: "3.9-slim"
        {% else %}
        PYTHON_IMAGE_TAG: "3.9-slim"
        {% endif %}
    command: '{% if cookiecutter.create_cli == "yes" %}--help{% else %}--config /app/config/config.yml{% endif %}'
    tty: true
