version: '3'

services:
  {{ cookiecutter.project_slug }}:
    image: 'at/{{ cookiecutter.project_slug }}:latest'
    build:
      context: .{% if cookiecutter.package_manager != 'poetry' %}
      args:
        PYTHON_IMAGE_TAG: {% if cookiecutter.package_manager == 'conda' %}"4.8.2"{% else %}"3.8-stretch"{% endif %}{% endif %}
    command: '{% if cookiecutter.create_cli == 'yes' %}--help{% endif %}'
    tty: true
