ARG IMAGE_TAG=22.9.0-2

FROM condaforge/mambaforge:${IMAGE_TAG}

LABEL maintainer="{{ cookiecutter.company_name if cookiecutter.company_name else cookiecutter.full_name }}"

WORKDIR /{{cookiecutter.module_name}}
COPY environment.yml .

RUN conda config --set channel_priority strict && \
    mamba env create -n {{cookiecutter.module_name}}_env -f environment.yml

# Make RUN commands use the new environment (see: https://pythonspeed.com/articles/activate-conda-dockerfile/)
SHELL ["mamba", "run", "-n", "{{cookiecutter.module_name}}_env", "/bin/bash", "-c"]

COPY . .
RUN python setup.py install

# ENTRYPOINT doesn't use the same shell as RUN so you need the conda stuff
ENTRYPOINT ["mamba", "run", "-n", "{{cookiecutter.module_name}}_env", "python", "-OO", "-m", "{{ cookiecutter.module_name }}"]
