ARG PYTHON_VERSION=3.13
FROM python:${PYTHON_VERSION}-bullseye
LABEL maintainer="{{ cookiecutter.company_name if cookiecutter.company_name else cookiecutter.full_name }}"

RUN pip install poetry && poetry config virtualenvs.create false
WORKDIR /app
COPY pyproject.toml poetry.lock ./
RUN poetry install --only main --no-root --no-interaction && \
    poetry cache clear pypi --all
COPY ./src /app/src
RUN poetry install --only-root

{%- if cookiecutter.ui_framework == 'chainlit' %}
EXPOSE 8000
CMD ["chainlit", "run", "src/{{ cookiecutter.module_name }}/ui/app.py", "-h"]
{%- elif cookiecutter.ui_framework == 'streamlit' %}
EXPOSE 8501
CMD ["streamlit", "run", "src/{{ cookiecutter.module_name }}/ui/app.py"]
{%- else %}
ENTRYPOINT ["python", "-OO", "-m", "{{ cookiecutter.module_name }}"]
{%- endif %}
