# uv.toml - Configuration file for uv package manager

[project]
name = "{{ cookiecutter.project_slug }}"
version = "0.1.0"
description = "{{ cookiecutter.project_short_description }}"
authors = ["{{ cookiecutter.full_name }} <{{ cookiecutter.email }}>"]
license = "proprietary"
# Define the package(s) from the src folder.
packages = [{ include = "{{ cookiecutter.module_name }}", from = "src" }]
include = ["src/{{ cookiecutter.module_name }}/res/*"]

{% if cookiecutter.create_cli == "yes" %}
[project.scripts]
# CLI entrypoint: when uv installs the project, this script is made available.
{{ cookiecutter.project_slug }} = "{{ cookiecutter.module_name }}.main:app"
{% endif %}

[dependencies]
python = ">=3.11,<4.0"
{% if cookiecutter.config_file == 'hocon' %}
pyhocon = "^0.3.59"
{% elif cookiecutter.config_file == 'yaml' %}
pyyaml = "^6.0"
{% endif %}
{% if cookiecutter.create_cli == 'yes' %}
typer = { extras = ["all"], version = "^0.9.0" }
{% endif %}

[dev-dependencies]
pytest = "^7.0"
pytest-cov = "^4.0"
pre-commit = "^3.0"
{% if cookiecutter.use_notebooks == 'yes' %}
jupyterlab = "^3.5"
{% endif %}
{% if cookiecutter.code_formatter == 'black' %}
black = "^23.11"
{% else %}
ruff = "^0.1.7"
{% endif %}
isort = "^5.12.0"

# Optional: Test settings (if uv supports this configuration)
[test]
minversion = "7.0"
testpaths = ["tests"]
