[tool.poetry]
name = "at-python-template"
version = "1.2.2"
description = "This is the official Python Project Template of Alexander Thamm GmbH (AT)"
authors = [
    "Christian Baur <christian.baur@alexanderthamm.com>",
    "Honza Bílek <jan.bilek@alexanderthamm.com>",
#    "Sebastian Straub <sebastian.straub@alexanderthamm.com>",
#    "Steffen Bunzel <steffen.bunzel@alexanderthamm.com>",
#    "Hans Rauer <hans.rauer@alexanderthamm.com>",
#    "Simon Weiß <simon.weiss@alexanderthamm.com>",
]
license = "Apache License, Version 2.0"
readme = "README.md"
packages = [{ include = "{{cookiecutter.module_name}}", from = "{{cookiecutter.project_slug}}/src" }]

[tool.poetry.dependencies]
python = "^3.10"
cookiecutter = "^2.3"
pre-commit = "^4.3.0"
pytest-mock = "^3.12"
pyhocon = "^0.3.60"
pyyaml = "^6.0"
typer = "^0.16.1"
setuptools = "^80.9.0"
requests = ">=2.32.4"
urllib3 = ">=2.6.3"
wheel = ">=0.46.2"
filelock = ">=3.20.3"
virtualenv = ">=20.36.1"

[tool.poetry.group.dev.dependencies]
pytest = "^8.4.1"
pytest-cov = "^6.2.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
