[tool.poetry]
name = "at-python-template"
version = "1.3.0"
description = "This is the official Python Project Template of Alexander Thamm GmbH (AT)"
authors = [
    "Christian Baur <christian.baur@alexanderthamm.com>",
    "Honza Bílek <jan.bilek@alexanderthamm.com>",
#    "Sebastian Straub <sebastian.straub@alexanderthamm.com>",
#    "Steffen Bunzel <steffen.bunzel@alexanderthamm.com>",
#    "Hans Rauer <hans.rauer@alexanderthamm.com>",
#    "Simon Weiß <simon.weiss@alexanderthamm.com>",
]
license = "Apache License, Version 2.0"
readme = "README.md"
packages = [{ include = "{{cookiecutter.module_name}}", from = "{{cookiecutter.project_slug}}/src" }]

[tool.poetry.dependencies]
python = "^3.10"
cookiecutter = "^2.6"
pre-commit = "^4.5.1"
pytest-mock = "^3.15.1"
pyhocon = "^0.3.61"
pyyaml = "^6.0.3"
omegaconf = "^2.3.0"
typer = "^0.21.1"
setuptools = "^80.10.2"
requests = ">=2.32.5"
urllib3 = ">=2.6.3"
wheel = "~=0.46.3"
filelock = ">=3.20.3"
virtualenv = ">=20.36.1"

[tool.poetry.group.dev.dependencies]
pytest = "^9.0.2"
pytest-cov = "^7.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
