# Pipeline which copies docker image from the Container Registry in a (previous) environment to the next environment
# This will be used to deploy the image DEV -> QA -> PROD
#
# expected parameters:
# ACR_PREVIOUS : Azure Container Registry to pull Docker image from
# ACR_NEXT: Azure Container Registry to push Docker image to
# ACR_SUB_PREVIOUS: Service Connection used for authentication with Container Registry OLD
# ACR_SUB_NEXT: Service Connection used for authentication with Container Registry NEW
# REPOSITORY: The repository to push and pull to/from in the Container Registries, should be the same for all environments to avoid complexity
# IMAGE_COUNT: Number of last images to retain, all others are deleted

parameters:
- name: ACR_PREVIOUS 
  type: string
- name: ACR_NEXT
  type: string
- name: ACR_SUB_PREVIOUS
  type: string
- name: ACR_SUB_NEXT
  type: string
- name: REPOSITORY
  type: string
- name: IMAGE_COUNT
  type: number
- name: SUBSCRIPTION
  type: string

steps:
- task: Docker@2
  displayName: Pull image from container repository of previous environment
  inputs:
    containerRegistry: ${{ parameters.ACR_SUB_PREVIOUS }}
    repository: ${{ parameters.REPOSITORY }}
    command: pull
    arguments: ${{ parameters.ACR_PREVIOUS }}/${{ parameters.REPOSITORY }}:$(Build.BuildId)

- bash: docker tag ${{ parameters.ACR_PREVIOUS }}/${{ parameters.REPOSITORY }}:$(Build.BuildId) ${{ parameters.ACR_NEXT }}/${{ parameters.REPOSITORY }}:$(Build.BuildId)
  displayName: Promote Docker image to registry of next environment

- task: Docker@2
  displayName: Push Image to container repository of next environment
  inputs:
    containerRegistry: ${{ parameters.ACR_SUB_NEXT }}
    repository: ${{ parameters.REPOSITORY }}
    command: push
    tags: $(Build.BuildId)

- template: delete-old-images.yml
  parameters:
    ACR: ${{ parameters.ACR_NEXT }}
    SUBSCRIPTION: ${{ parameters.SUBSCRIPTION }}
    REPOSITORY: ${{ parameters.REPOSITORY }}
    IMAGE_COUNT: ${{ parameters.IMAGE_COUNT}}
